version: '3.3'
services:
    simulator:
        image: idslabautosec/carla-fog:v1
        logging:
          options:
            max-size: "10m"
            max-file: "3"
        privileged: true
        environment:
            SDL_VIDEODRIVER: x11
            DISPLAY: $DISPLAY
        network_mode: host
        user: carla
        command: /home/carla-fog/CarlaUE4.sh
        volumes:
            - /home/amax/workspace:/home/workspace/
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /etc/localtime:/etc/localtime
            - /etc/timezone:/etc/timezone
            - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: "all"
                  capabilities: [compute,utility,graphics,display]
